# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 7
language: 'en-us'

# Website info
name: 'Devon C. Estes'

# Author's info
author: 'Devon C. Estes'
nickname: devon
bio: 'Ruby and Elixir developer, chess player, and American living in Germany'
location: 'Berlin, Germany'
url: 'http://www.devonestes.com'
image: 'assets/images/cropped_headshot.jpg'
short_url: 'http://www.devonestes.com'

baseurl: /
permalink: /:title/

# gems and other configs
gems:
  - jekyll-paginate
  - kramdown 

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - config.ru
  - Procfile

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      logo: "assets/images/logo.png"
      navigation: True
      subclass: 'post tag-test tag-content'
      categories: 'devon'
